name: docker-image-build

on:
  push:
    branches:
      - 'main'
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@main
    
    - name: Log into Docker Hub
      uses: docker/login-action@master
      with: 
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
      
    - name: Build and Push the Docker Image
      uses: docker/build-push-action@master
      with:
        context: .
        push: true
        tags: ccmpbll/prometheus-docker:latest
